#### ---- config file ---- ####
#---- This file contains all the configuration parameters to be passed as a command line
#---- argument to main.py, i.e. python3 main.py -config configs.yaml.

#---- All values NOT populated in this file require math or python packages, so they 
#---- are updated in utils/update_config.py

#---- If you want to run the experiment which identifies the characteristics,
#---- let experiment.animate = 0

#---- If you want to generate an animation of the fields through a single pillar, let
#---- experiment.animate = 1. an mp4 will be generated and sent to /src/single_pillar/vis.



####----- Simulation params for single pillar simulation -----###
#-----------------------------------------------------------###

resolution : 20 

cell :
  x : 0.680
  y : 0.680
  z :

cell_size :

wavelength : 1.55

freq : 

k_point : 

symmetries:

####----- Geometry params for single pillar simulation ----- ###
#----------------------------------------------------------- ###

#       ________________
#      |                |
#      |                |<--- PDMS 
#      |     ______     |
#      |    |      |    |
#      |    |      |<---|- Amorphous Silicon - pillar radii range is 0.075 - 0.250 micron
#      |    |      |    |
#      |____|______|___ |
#      |                |
#      |                |<--- Fused Silica (substrate)
#      |________________|

#---------------------------------------------------------- ###

fusedSilica :
  n : 1.44
  width : 0.780
  center :

PDMS :
  n : 1.4
  width : 1.560
  center :

amorphousSi :
  n : 3.48
  height : 1.020
  center :
  radius_min : 0.075
  radius_max : 0.250

pml:
  thickness : 0.780
  layers :

a : 0.680   # lattice period 

####----- Source params for single pillar simulation -----###
#---------------------------------------------------------###

source :
  center: 
  cmpt : 

####----- Flux region params for single pillar simulation -----###
#--------------------------------------------------------------###

flux :
  nfreq : 1
  df : 0
  center :

##-- Experimental params for obtaining single pillar characteristics --##
#--------------------------------------------------------------------####

experiment :
  num : 8 # this is the number of pillars we will build
  animate : 0

vis :
  fps : 20
